# -*- coding: utf-8 -*-
"""ARIMAPrivateHousingStarts2024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_KyrxTleB8D-EDkazOlHzM8c4I3KY3bE
"""

# Access the data set; `sheet_name=None` means import all sheets from the workbook.
from pandas import read_excel
data=read_excel("https://www.census.gov/construction/nrc/xls/starts_cust.xlsx", sheet_name=None, header=[5, 5, 5, 5])

# Extract rows 0 to 779 and columns 0 to 1 from the "Seasonally Adjusted" sheet.
# Note: Change 780 to 781 to include January 2024.
df = data["Seasonally Adjusted"].iloc[0:780, 0:2]
# Update the column headers
df.columns = ["Month", "PHS"]
# Get the phs `Series` by itself
phs = df["PHS"]
# Label the rows of `phs` by the month
phs.index = df["Month"]
print(phs)

# Do an initial exploratory plot
from matplotlib import pyplot as plt
plt.plot(phs)
plt.show()

from pandas import DataFrame
from statsmodels.tsa.api import acf, pacf
def findAcf(series):
    acf_vals, confints = acf(series, nlags=20, alpha=.05)
    lower = confints.take(indices=0, axis=1)
    upper = confints.take(indices=1, axis=1)
    plt.plot(acf_vals, color="gray", label="ACF")
    plt.plot(lower, color="black", linestyle="dashed", label="Lower")
    plt.plot(upper, color="black", linestyle="dotted", label="Upper")
    plt.legend()
    plt.show()
    print(DataFrame({"ACF": acf_vals, "Lower": lower, "Upper": upper}))

def findPacf(series):
    pacf_vals, confints = pacf(series, nlags=20, alpha=.05)
    lower = confints.take(indices=0, axis=1)
    upper = confints.take(indices=1, axis=1)
    plt.plot(pacf_vals, color="gray", label="PACF")
    plt.plot(lower, color="black", linestyle="dashed", label="Lower")
    plt.plot(upper, color="black", linestyle="dotted", label="Upper")
    plt.legend()
    plt.show()
    print(DataFrame({"PACF": pacf_vals, "Lower": lower, "Upper": upper}))

def diffSeries(series):
    return [series[i+1]-series[i] for i in range(len(series) - 1)]

findAcf(diffSeries(phs))

findPacf(phs)